# Generated by Django 4.2.28 on 2026-04-16 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260403_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='proposed_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='proposed_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='proposed_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='proposed_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='proposed_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='proposed_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
