# Generated by Django 4.2.28 on 2026-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsessions', '0004_sessionmessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
