# Generated by Django 4.2.28 on 2026-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsessions', '0005_session_cancelled_at_session_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
